name: Deploy Worker (Explicit Secrets)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Upload Secrets Manually
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          echo "${{ secrets.GOOGLE_API_KEY }}" | wrangler secret put GOOGLE_API_KEY
          echo "${{ secrets.MS_TENANT_ID }}" | wrangler secret put MS_TENANT_ID
          echo "${{ secrets.MS_CLIENT_ID }}" | wrangler secret put MS_CLIENT_ID
          echo "${{ secrets.MS_CLIENT_SECRET }}" | wrangler secret put MS_CLIENT_SECRET
          echo "${{ secrets.MS_USER_ID }}" | wrangler secret put MS_USER_ID

      - name: Deploy Worker Code
        run: npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

