# Cloudflare Worker 配置文件
# [!!] 已更新: 添加了 R2 存储桶绑定

name = "cfzy"
main = "src/index.mjs"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]

# [!! NEW !!] R2 存储桶绑定
# 用于临时存储 >100MB 的大型文件上传
[[r2_buckets]]
binding = "R2_BUCKET" # 在 src/index.mjs 中使用 env.R2_BUCKET
bucket_name = "CF_R2_BUCKET_NAME" # [!!!] 占位符, 由 deploy.yml 注入

# KV 命名空间绑定
# 用于存储登录验证码和会话
[[kv_namespaces]]
binding = "AUTH_KV" # 在 src/index.mjs 中使用 env.AUTH_KV
id = "CF_KV_NAMESPACE_ID" # [!!!] 占位符, 由 deploy.yml 注入

# 环境变量 (Secrets)
# 这些值将由 deploy.yml 在部署时从 GitHub Secrets 注入
# (注意: R2 密钥不在这里, 它们用于 S3 客户端)
[vars]
GOOGLE_API_KEY = "GOOGLE_API_KEY"
MS_CLIENT_ID = "MS_CLIENT_ID"
MS_CLIENT_SECRET = "MS_CLIENT_SECRET"
MS_TENANT_ID = "MS_TENANT_ID"
MS_USER_ID = "MS_USER_ID"
MS_ONEDRIVE_BASE_PATH = "MS_ONEDRIVE_BASE_PATH"
APP_TITLE = "APP_TITLE"
TEACHER_WHITELIST = "TEACHER_WHITELIST"
# [!! NEW !!] R2 相关的 secrets (在 worker 脚本内部使用)
CF_R2_BUCKET_NAME = "CF_R2_BUCKET_NAME" 
CF_R2_ACCESS_KEY_ID = "CF_R2_ACCESS_KEY_ID"
CF_R2_SECRET_ACCESS_KEY = "CF_R2_SECRET_ACCESS_KEY"
CLOUDFLARE_ACCOUNT_ID = "CLOUDFLARE_ACCOUNT_ID" # S3 Client 需要 Account ID

