name = "gemini-onedrive-analyzer"
main = "worker.js"
compatibility_date = "2023-10-30"

# This build configuration is ESSENTIAL for multi-module support.
[build]
command = ""
[build.upload]
format = "modules"

