# Cloudflare Worker 配置文件
# (v3 - 邮件验证, < 100MB 标准上传方案)

name = "cfzy"
main = "src/index.mjs"
compatibility_date = "2024-05-01"
compatibility_flags = ["nodejs_compat"]



# 环境变量 (Secrets)
# 这些值将由 deploy.yml 在部署时从 GitHub Secrets 注入
[vars]
GOOGLE_API_KEY = "${GOOGLE_API_KEY}"
MS_CLIENT_ID = "${MS_CLIENT_ID}"
MS_CLIENT_SECRET = "${MS_CLIENT_SECRET}"
MS_TENANT_ID = "${MS_TENANT_ID}"
MS_USER_ID = "${MS_USER_ID}"
MS_ONEDRIVE_BASE_PATH = "${MS_ONEDRIVE_BASE_PATH}"
APP_TITLE = "${APP_TITLE}"
TEACHER_WHITELIST = "${TEACHER_WHITELIST}"

