name = "gemini-onedrive-analyzer"
main = "worker.js"
compatibility_date = "2023-10-30"

# Added build configuration for multi-module support
[build]
command = "" # No build step is needed for plain JS
upload = {
  format = "modules",
  main = "./worker.js" # Specify the entry point for the module bundle
}
