name: Deploy Worker with Diagnostics

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Diagnostic - Attempt to List Secrets
        id: diagnostic_step
        run: npx wrangler secret list
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        # This allows the workflow to continue even if this step fails, so we can see the log.
        continue-on-error: true

      - name: Deploy Worker
        # This step will only run if the diagnostic step above was successful.
        if: steps.diagnostic_step.outcome == 'success'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: [
            'GOOGLE_API_KEY',
            'MS_TENANT_ID',
            'MS_CLIENT_ID',
            'MS_CLIENT_SECRET',
            'MS_USER_ID'
          ]

