name = "cfzy"
main = "worker.js"
compatibility_date = "2023-10-30"

# This build configuration is ESSENTIAL for multi-module support.
# It tells Wrangler to package all necessary files from the directory.
[build]
command = ""
[build.upload]
format = "modules"
