# GitHub Actions 工作流: 部署 Cloudflare Worker
# [!!] 已修复: 移除了 R2 依赖和所有无效的命令行参数

name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main # 仅在推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 

      - name: Install Dependencies
        run: npm install # 安装 package.json 中的依赖

      - name: Deploy Worker
        # [!!] 修复:
        # wrangler deploy 命令不需要 --var 或 --kv。
        # 它会自动读取 wrangler.toml 文件, 
        # 并从下面的 'env:' 块中查找所有需要的环境变量。
        run: npx wrangler deploy
        env:
          # Cloudflare 部署凭据
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
          # --- 以下变量必须与 wrangler.toml 匹配 ---
          
          # KV 绑定密钥 (来自 [[kv_namespaces]])
          CF_KV_NAMESPACE_ID: ${{ secrets.CF_KV_NAMESPACE_ID }}
          
          # 应用密钥 (来自 [vars])
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          MS_CLIENT_ID: ${{ secrets.MS_CLIENT_ID }}
          MS_CLIENT_SECRET: ${{ secrets.MS_CLIENT_SECRET }}
          MS_TENANT_ID: ${{ secrets.MS_TENANT_ID }}
          MS_USER_ID: ${{ secrets.MS_USER_ID }}
          MS_ONEDRIVE_BASE_PATH: ${{ secrets.MS_ONEDRIVE_BASE_PATH }}
          APP_TITLE: ${{ secrets.APP_TITLE }}
          TEACHER_WHITELIST: ${{ secrets.TEACHER_WHITELIST }}

