name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main # 仅在 main 分支被推送时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache: 'npm' # 禁用缓存以避免 'package-lock.json' 缺失的错误

      - name: Install Dependencies
        run: npm install # 此步骤将安装 package.json 中列出的所有依赖项

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # 在这里设置所有需要的 Secrets
          # 注意：MS_REFRESH_TOKEN 已被移除
          secrets: |
            GOOGLE_API_KEY
            MS_CLIENT_ID
            MS_CLIENT_SECRET
            MS_TENANT_ID
            MS_USER_ID
        env:
          # 将 GitHub Secrets 映射到环境变量，以便 Wrangler 可以读取它们
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          MS_CLIENT_ID: ${{ secrets.MS_CLIENT_ID }}
          MS_CLIENT_SECRET: ${{ secrets.MS_CLIENT_SECRET }}
          MS_TENANT_ID: ${{ secrets.MS_TENANT_ID }}
          MS_USER_ID: ${{ secrets.MS_USER_ID }}

