# .github/workflows/deploy.yml
#
# 这个 GitHub Actions 工作流会在您推送 (push) 到 'main' 分支时
# 自动部署您的 Cloudflare Worker。

name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main  # 您的默认分支可能是 'master'，请按需修改

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 使用一个最新的 Node.js LTS 版本
          cache: 'npm' # 启用 npm 缓存

      - name: Install Dependencies
        # 这一步至关重要！
        # 它会读取 package.json 文件并安装所有必需的包
        # (wrangler, @google/generative-ai, unzipit)
        run: npm install

      - name: Deploy
        # 运行部署命令
        # npx 会找到 node_modules 中安装的 wrangler
        # 它会从 GitHub Secrets 中读取所有密钥
        run: npx wrangler deploy
        env:
          # 用于 GitHub Actions 验证 Cloudflare 账户
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          
          # 以下密钥将被 Wrangler 自动上传为 Worker 的 Secrets
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          MS_CLIENT_ID: ${{ secrets.MS_CLIENT_ID }}
          MS_CLIENT_SECRET: ${{ secrets.MS_CLIENT_SECRET }}
          MS_TENANT_ID: ${{ secrets.MS_TENANT_ID }}
          MS_USER_ID: ${{ secrets.MS_USER_ID }}
          # MS_REFRESH_TOKEN 由您手动管理，此处不再包含

